### ISSUE TITLE
Hi, I got an error after running the leetcode gpt extension

### ISSUE THREAD

**Issue by alhussain-shaikh** [rpidanny/leetcode-gpt#7]
![image](https://github.com/rpidanny/leetcode-gpt/assets/116242196/bbb25678-dcf9-4cbf-abf4-38437d944728)

**Comment by rpidanny** [comment]
Hi @alhussain-shaikh, thanks for reporting the issue, investigating now 👀

**Comment by rpidanny** [comment]
Hi @alhussain-shaikh , can you try the latest release? The issue should be fixed now.

**Comment by alhussain-shaikh** [comment]
Thank You @rpidanny
