### ISSUE TITLE
Hi,but now it is showing Request failed

### ISSUE THREAD

**Issue by alhussain-shaikh** [rpidanny/leetcode-gpt#9]
![image](https://github.com/rpidanny/leetcode-gpt/assets/116242196/00c45afe-a366-40cd-8518-21a72ea3c42e)
I have added the API KEY also

**Comment by rpidanny** [comment]
Hi @alhussain-shaikh , that's strange, will have a look later today.

**Comment by rpidanny** [comment]
Is the 404 from ChatGPT API call? You can find that in the network tab.

**Comment by alhussain-shaikh** [comment]
> Is the 404 from ChatGPT API call? You can find that in the network tab.

yes,
![image](https://github.com/rpidanny/leetcode-gpt/assets/116242196/ea112545-6864-465b-b078-0035547a042a)

**Comment by rpidanny** [comment]
Can you share the response from chatgpt?

**Comment by alhussain-shaikh** [comment]
> Can you share the response from chat

It is showing that API is never used

**Comment by rpidanny** [comment]
> > Can you share the response from chat
> 
> It is showing that API is never used

No, I mean the response from the `completions` fetch api call that you see in your network tab. It should show why you got a 404. Perhaps choosing an invalid model?

**Comment by alhussain-shaikh** [comment]
![image](https://github.com/rpidanny/leetcode-gpt/assets/116242196/5c0db652-30cb-420b-8a0b-9574f53e1bff)

**Comment by alhussain-shaikh** [comment]
> 
> No, I mean the response from the `completions` fetch api call that you see in your network tab. It should show why you got a 404. Perhaps choosing an invalid model?
![image](https://github.com/rpidanny/leetcode-gpt/assets/116242196/209eb1dc-0b9f-477d-9327-826d6949d93b)

**Comment by rpidanny** [comment]
<img width="696" alt="Screenshot 2023-10-30 at 12 08 00" src="https://github.com/rpidanny/leetcode-gpt/assets/6696862/fe733c47-f955-4363-b2d0-87824124e95c">

Looking at the response from chatgpt like this would be more useful as it should tell you what exactly is going wrong. Perhaps some issues with the model you are using?

**Comment by alhussain-shaikh** [comment]
![image](https://github.com/rpidanny/leetcode-gpt/assets/116242196/0f465e8c-321e-428a-b98d-bd45eb78576b)
Do I need to buy any plan of chatgpt 3.5 but it is free of cost na?

**Comment by rpidanny** [comment]
Nope, you pay for API usage.
